name: Build and Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  backend-build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build Backend
      working-directory: ./backend
      run: cargo build --verbose
    - name: Run Backend Tests
      working-directory: ./backend
      run: cargo test --verbose

  frontend-build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '21'
    - name: Install Dependencies
      working-directory: ./frontend/finance-tracker
      run: npm install
    - name: Build Frontend
      working-directory: ./frontend/finance-tracker
      run: npm run build